<?php

namespace PhpPdgAnalysis\Analysis;

class LibraryInfo implements DirectoryAnalysisInterface {
	public function analyse($librarydir) {
		$info = [
			"cakephp" => [
				"name" => "CakePHP",
				"version" => "3.2.8",
				"release" => "24-04-2016",
				"php" => "5.5.9",
				"sloc" => 139620,
				"description" => "Application Framework",
				"autoloading" => "PSR-4",
				'hillsEval' => null,
				"hillsIncludes" => 124,
				'hillsVarVar' => 20,
			],
			"CodeIgniter" => [
				"name" => "CodeIgniter",
				"version" => "3.0.6",
				"release" => "21-03-2016",
				"php" => "5.2.4",
				"sloc" => 29770,
				"description" => "Application Framework",
				"autoloading" => '',
				'hillsEval' => null,
				"hillsIncludes" => 69,
				'hillsVarVar' => 20,
			],
			"doctrine2" => [
				"name" => "Doctrine ORM",
				"version" => "2.5.0",
				"release" => "02-04-2016",
				"php" => "5.4.0",
				"sloc" => 85591,
				"description" => "ORM",
				"autoloading" => "PSR-0",
				'hillsEval' => null,
				"hillsIncludes" => 56,
				'hillsVarVar' => 0,
			],
			"drupal" => [
				"name" => "Drupal",
				"version" => "8.1.0",
				"release" => "20-04-2016",
				"php" => "5.5.9",
				"sloc" => 480861,
				"description" => "CMS",
				"autoloading" => "PSR-4",
				'hillsEval' => null,
				"hillsIncludes" => 172,
				'hillsVarVar' => 1,
			],
			"fabric" => [
				"name" => "Fabric",
				"varion" => "1.6",
				"release" => "08-07-2016",
				"php" => "5.5.0",
				"sloc" => 57573,
				"description" => "Application Framework",
				"autoloading" => "PSR-0, Custom",
				'hillsEval' => null,
				'hillsIncludes' => null,
				'hillsVarVar' => null,
			],
			"gallery3" => [
				"name" => "Gallery",
				"version" => "3.0.9",
				"release" => "26-06-2013",
				"php" => "5.2.3",
				"sloc" => 44758,
				"description" => "Photo Management",
				"autoloading" => 'Custom',
				'hillsEval' => null,
				"hillsIncludes" => 44,
				'hillsVarVar' => 7,
			],
			"joomla-cms" => [
				"name" => "Joomla",
				"version" => "3.5.1",
				"release" => "05-04-2016",
				"php" => "5.3.10",
				"sloc" => 347423,
				"description" => "CMS",
				"autoloading" => 'Custom',
				'hillsEval' => null,
				"hillsIncludes" => 354,
				'hillsVarVar' => 2,
			],
			"kohana" => [
				"name" => "Kohana",
				"version" => "3.3.5",
				"release" => "10-03-2016",
				"php" => "5.3.3",
				"sloc" => 30738,
				"description" => "Application Framework",
				"autoloading" => 'Custom',
				'hillsEval' => null,
				"hillsIncludes" => 52,
				'hillsVarVar' => 7,
			],
			"magento2" => [
				"name" => "Magento",
				"version" => "2.0.4",
				"release" => "31-03-2016",
				"php" => "5.5.0",
				"sloc" => 1023247,
				"description" => "Online Retail",
				"autoloading" => 'PSR-0, PSR-4, Custom',
				'hillsEval' => null,
				'hillsIncludes' => null,
				'hillsVarVar' => null,
			],
			"mediawiki-1.26.2" => [
				"name" => "MediaWiki",
				"version" => "1.26.2",
				"release" => "21-12-2015",
				"php" => "5.3.3",
				"sloc" => 400416,
				"description" => "Wiki",
				"autoloading" => 'PSR-0, Custom',
				'hillsEval' => null,
				"hillsIncludes" => 554,
				'hillsVarVar' => 11,
			],
			"moodle" => [
				"name" => "Moodle",
				"version" => "3.0.3",
				"release" => "12-03-2015",
				"php" => "5.4.4",
				"sloc" => 1167840,
				"description" => "Online Learning",
				"autoloading" => 'Custom',
				'hillsEval' => null,
				"hillsIncludes" => 7744,
				'hillsVarVar' => 39,
			],
			"oscommerce2" => [
				"name" => "osCommerce",
				"version" => "2.3.4",
				"release" => "06-06-2014",
				"php" => "4.0.0",
				"sloc" => 60003,
				"description" => "Online Retail",
				"autoloading" => '',
				'hillsEval' => null,
				"hillsIncludes" => 683,
				'hillsVarVar' => 89,
			],
			"pear-core" => [
				"name" => "PEAR",
				"version" => "1.10.1",
				"release" => "17-10-2015",
				"php" => "5.4.0",
				"sloc" => 48872,
				"description" => "Component Framework",
				"autoloading" => '',
				'hillsEval' => null,
				"hillsIncludes" => 211,
				'hillsVarVar' => 1,
			],
			"phpbb-app" => [
				"name" => "phpBB",
				"version" => "3.1.5",
				"release" => "03-05-2015",
				"php" => "5.3.3",
				"sloc" => 183293,
				"description" => "Bulletin Board",
				"autoloading" => 'Custom',
				'hillsEval' => null,
				"hillsIncludes" => 404,
				'hillsVarVar' => 82,
			],
			"phpmyadmin" => [
				"name" => "phpMyAdmin",
				"version" => "4.6.0",
				"release" => "17-05-2016",
				"php" => "5.5.0",
				"sloc" => 202399,
				"description" => "Database Administration",
				"autoloading" => 'PSR-4, Custom',
				'hillsEval' => null,
				"hillsIncludes" => 819,
				'hillsVarVar' => 112,
			],
			"silverstripe-framework" => [
				"name" => "SilverStripe",
				"version" => "3.3.1",
				"release" => "29-02-2016",
				"php" => "5.3.3",
				"sloc" => 183293,
				"description" => "CMS",
				"autoloading" => 'PSR-0, Custom',
				'hillsEval' => null,
				"hillsIncludes" => 373,
				'hillsVarVar' => 3,
			],
			"smarty" => [
				"name" => "Smarty",
				"version" => "3.1.29",
				"release" => "21-12-2015",
				"php" => "5.2.0",
				"sloc" => 17282,
				"description" => "Template Engine",
				"autoloading" => 'Custom',
				'hillsEval' => null,
				"hillsIncludes" => 38,
				'hillsVarVar' => 40,
			],
			"squirrelmail" => [
				"name" => "Squirrel Mail",
				"version" => "1.4.22",
				"release" => "12-07-2011",
				"php" => "4.1.0",
				"sloc" => 26045,
				"description" => "Webmail",
				"autoloading" => '',
				'hillsEval' => null,
				"hillsIncludes" => 426,
				'hillsVarVar' => 24,
			],
			"symfony" => [
				"name" => "Symfony",
				"version" => "3.0.4",
				"release" => "30-03-2016",
				"php" => "5.5.9",
				"sloc" => 202757,
				"description" => "Application Framework",
				"autoloading" => 'PSR-4, Custom',
				'hillsEval' => null,
				"hillsIncludes" => 96,
				'hillsVarVar' => 0,
			],
			"WordPress" => [
				"name" => "WordPress",
				"version" => "4.5",
				"release" => "12-04-2016",
				"php" => "5.6.0",
				"sloc" => 160039,
				"description" => "Blog",
				"autoloading" => 'Custom',
				'hillsEval' => null,
				"hillsIncludes" => 589,
				'hillsVarVar' => 37,
			],
			"zf2" => [
				"name" => "Zend Framework",
				"version" => "2.5.3",
				"release" => "27-01-2016",
				"php" => "5.5.0",
				"sloc" => 169447,
				"description" => "Application Framework",
				"autoloading" => 'PSR-0',
				'hillsEval' => null,
				"hillsIncludes" => 12829,
				'hillsVarVar' => 7,
			],
		];
		$filename = pathinfo($librarydir, PATHINFO_BASENAME);
		return isset($info[$filename]) ? $info[$filename] : [];
	}

	public function getSuppliedAnalysisKeys() {
		return [
			"name",
			"version",
			"release",
			"php",
			"sloc",
			"description",
			"autoloading",
			"hillsEval",
			'hillsIncludes',
			'hillsVarVar',
		];
	}
}